name: Substreams
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supplypike/setup-bin@v4
        with:
          uri: "https://github.com/streamingfast/substreams/releases/download/v1.3.2/substreams_linux_x86_64.tar.gz"
          name: "substreams"
          version: "1.3.2"
      - run: make
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            *.spkg
